name: DataFile
version: 0.0.3
author: CrimsonDawn45
main: me.crimsondawn45.datafileplugin.DataFilePlugin
api-version: 1.17
description: Plugin for easily storing data in .yml files.
depend: [floodgate]
commands:
  datafile:
    usage: /datafile [list | get | set] <datafile> <Path> <value>
    permission: datafile.edit
  seen:
    usage: /seen <player>